apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
spec:
  project: default

  source:
    repoURL: https://github.com/tshamo/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc

  #syncPolicy:
  #  syncOptions:
  #  - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true