apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: hello-world

images:
- name: taulant101/hello-app
  newTag: "3.0"

replicas:
- name: hello-world
  count: 1

patches:
- target:
    kind: Ingress
    name: hello-world-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: staging.hello-world.local

- target:
    kind: Deployment
    name: hello-world
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: staging